#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=15

# check_group "Name" gates a block of manual test assertions. On a failure it
# captures which assertion broke, so the closing summary names it instead of
# just reporting that something went wrong.
check_group() {
  local name="$1" detail=""
  if confirm "Did every check above pass?"; then
    printf '  %s✓ %s%s\n' "$GREEN" "$name" "$RESET"
  else
    printf '  %s✗ %s%s\n' "$RED" "$name" "$RESET"
    ask FAILED_DETAIL "Which check failed, and what happened?"
    detail="${FAILED_DETAIL:-unspecified}"
    SKIPPED+=("$name: $detail")
  fi
  pause
}

banner "Slack Ping Bot: app setup and manual test pass"

# ── Slack app creation ────────────────────────────────────────────────────
stage "Slack: create the app"
say "This wizard sets up the Slack app, runs the bot locally behind ngrok,"
say "and walks the 33-item manual test checklist."
note "The Slack dashboard is redesigned periodically. If a label below does not"
note "match what you see, the underlying setting still exists somewhere nearby."
open_url "https://api.slack.com/apps"
step "Click 'Create New App', then choose 'From scratch'."
step "Name it 'Ping Bot' (or anything you like)."
step "Pick the workspace you want to test in."
step "Click 'Create App'. You'll land on the app's Basic Information page."
pause "Created the app?"

# ── Bot token scopes ──────────────────────────────────────────────────────
stage "Slack: bot token scopes"
say "The bot needs four scopes. Three are added by hand here; 'commands'"
say "is granted automatically when you create the slash command in a later stage."
step "In the left sidebar, open 'OAuth & Permissions'."
step "Scroll to 'Scopes' → 'Bot Token Scopes' → 'Add an OAuth Scope'."
step "Add: chat:write    (send the ping message)"
step "Add: users:read    (resolve @username to a user ID)"
step "Add: im:write      (open a DM channel with the target)"
note "Add these under Bot Token Scopes, not User Token Scopes. User scopes act"
note "as you rather than as the bot, and the bot will fail to post."
pause "All three scopes added?"

# ── Install and capture the bot token ─────────────────────────────────────
stage "Slack: install to workspace"
say "Installing generates the bot token the app authenticates with."
step "Still on 'OAuth & Permissions', scroll to the top."
step "Click 'Install to Workspace', then 'Allow'."
step "Copy the 'Bot User OAuth Token'. It starts with xoxb-"
ask_secret SLACK_BOT_TOKEN "Paste the bot token (xoxb-...):"
if [[ -z "${SLACK_BOT_TOKEN:-}" ]]; then
  SKIPPED+=("SLACK_BOT_TOKEN was left empty; the bot cannot start without it")
  warn "no token captured; re-run this wizard once you have it"
elif [[ "$SLACK_BOT_TOKEN" != xoxb-* ]]; then
  warn "that does not start with xoxb-. A xoxp- token is a user token, not a bot token."
  SKIPPED+=("SLACK_BOT_TOKEN may be wrong: expected a xoxb- bot token")
  write_env SLACK_BOT_TOKEN "$SLACK_BOT_TOKEN"
else
  write_env SLACK_BOT_TOKEN "$SLACK_BOT_TOKEN"
fi
note "Not sent to GitHub Actions: the CI suite in issue #2 runs against VCR"
note "cassettes and mock_redis, so it never needs real Slack credentials."
pause

# ── Capture the signing secret ────────────────────────────────────────────
stage "Slack: signing secret"
say "The signing secret is what lib/slack_verifier.rb checks every request against."
step "In the left sidebar, open 'Basic Information'."
step "Scroll to 'App Credentials'."
step "Find 'Signing Secret' and click 'Show', then copy it."
ask_secret SLACK_SIGNING_SECRET "Paste the signing secret:"
if [[ -z "${SLACK_SIGNING_SECRET:-}" ]]; then
  SKIPPED+=("SLACK_SIGNING_SECRET was left empty; every request will be rejected with 401")
  warn "no signing secret captured; the bot will reject all Slack traffic"
else
  write_env SLACK_SIGNING_SECRET "$SLACK_SIGNING_SECRET"
fi
pause

# ── Redis ─────────────────────────────────────────────────────────────────
stage "Local: Redis"
say "Redis backs the rate limiter. It is optional: lib/rate_limiter.rb falls"
say "back to a thread-safe in-memory hash when Redis is unreachable."
step "To run it: docker run -d -p 6379:6379 redis:alpine"
step "To check it:  redis-cli ping     (expect PONG)"
note "Skipping Redis is fine for this pass, but note that the fallback resets"
note "counters on restart, so one test in the rate limiting stage covers it."
if confirm "Is Redis running?"; then
  write_env REDIS_URL "redis://localhost:6379/0"
else
  say "Continuing without Redis. The limiter will use the in-memory fallback."
  note "Leaving REDIS_URL as-is so the app tries and degrades on its own."
fi
pause

# ── Run the app ───────────────────────────────────────────────────────────
stage "Local: start the bot"
say "Start the app in a second terminal, so it keeps running while this wizard continues."
step "cd $(pwd)"
step "bundle install                              (once)"
step "bundle exec rerun 'rackup -p 4567'          (dev, auto-reload)"
note "For the production path instead: RUBY_YJIT_ENABLE=1 bundle exec puma -C config/puma.rb"
step "Check it: curl -s localhost:4567/           (expect a 200 and a JSON body)"
step "Check the version: curl -s localhost:4567/version"
pause "Is the bot running and answering on port 4567?"

# ── ngrok ─────────────────────────────────────────────────────────────────
stage "Local: expose the bot with ngrok"
say "Slack must reach your machine over HTTPS, so the local port needs a tunnel."
step "In a third terminal: ngrok http 4567"
step "Copy the https:// forwarding URL, e.g. https://abc123.ngrok-free.app"
note "Copy the https one, not http. Slack rejects plain-HTTP request URLs."
note "On the free plan this URL changes every time ngrok restarts, and the"
note "slash command has to be re-pointed each time. Re-run this wizard for that."
ask NGROK_URL "Paste the https ngrok URL (no trailing slash):"
if [[ -z "${NGROK_URL:-}" ]]; then
  SKIPPED+=("NGROK_URL was left empty; the slash command cannot be pointed anywhere")
  warn "no tunnel URL captured; Slack will not be able to reach the bot"
elif [[ "$NGROK_URL" != https://* ]]; then
  warn "that is not an https:// URL. Slack will reject it."
  SKIPPED+=("NGROK_URL is not https, so Slack will refuse the request URL")
  write_env NGROK_URL "$NGROK_URL"
else
  write_env NGROK_URL "${NGROK_URL%/}"
fi
note "Stored in $ENV_FILE only so a re-run can offer it as the default."
pause

# ── Slash command ─────────────────────────────────────────────────────────
stage "Slack: point /ping at the tunnel"
say "This is the stage that connects Slack to your running bot."
open_url "https://api.slack.com/apps"
step "Open your app, then 'Slash Commands' in the left sidebar."
step "Click 'Create New Command' (or edit /ping if it already exists)."
step "Command:      /ping"
step "Request URL:  ${NGROK_URL:-<your ngrok url>}/slack/commands"
step "Short description: Send someone a notification ping"
step "Usage hint:   [@username]"
step "Click 'Save'."
warn "If Slack shows a 'reinstall your app' banner, reinstall it now. Creating the"
warn "command adds the 'commands' scope, and the token is stale until you reinstall."
pause "Is /ping saved and pointing at your tunnel?"

# ── Manual test checklist: basic functionality ────────────────────────────
stage "Test 1/7: basic functionality"
ask PING_TEST_USER "Which @username will you ping for these tests?"
[[ -n "${PING_TEST_USER:-}" ]] && write_env PING_TEST_USER "$PING_TEST_USER"
say "Run each of these in Slack, then answer below."
step "Health endpoint: curl -s ${NGROK_URL:-http://localhost:4567}/ returns 200"
step "In a DM, '/ping' sends a notification to the other person"
step "In a channel, '/ping ${PING_TEST_USER:-@someone}' works"
step "The message appears and disappears in roughly 150ms"
step "The notification persists for the recipient after the message is deleted"
note "The last two are the point of this bot. Ask the recipient directly: the"
note "sender cannot see whether their notification survived the delete."
check_group "Basic functionality"

# ── Manual test checklist: username resolution ────────────────────────────
stage "Test 2/7: username resolution"
say "lib/user_resolver.rb parses and validates the target."
step "'/ping ${PING_TEST_USER:-@someone}' matches the exact username, case-insensitively"
step "'/ping <@U12345>' with a raw user ID works"
step "'/ping @definitely-not-a-real-user' shows an error"
step "A partial username shows an error rather than guessing a match"
note "The partial-match case matters: silently pinging the wrong person is worse"
note "than failing, so this must error rather than fuzzy-match."
check_group "Username resolution"

# ── Manual test checklist: validation ─────────────────────────────────────
stage "Test 3/7: validation"
say "Four things must be refused, per lib/user_resolver.rb."
step "You cannot ping yourself"
step "You cannot ping a bot user (try pinging this app)"
step "You cannot ping a deactivated user"
step "A malformed command shows a helpful error, not a stack trace"
check_group "Validation"

# ── Manual test checklist: rate limiting ──────────────────────────────────
stage "Test 4/7: rate limiting"
say "lib/rate_limiter.rb allows 3 pings per sender per rolling 60 seconds."
step "The first 3 pings in a minute all succeed"
step "The 4th ping fails with a rate limit error"
step "After waiting 60 seconds, a ping succeeds again"
step "With Redis stopped, the limit still applies (in-memory fallback)"
note "For the last one: docker stop the Redis container, then ping 4 times."
note "The limit should still bite. Restart Redis afterwards."
note "The limit is per sender only. Receiving pings is never limited."
check_group "Rate limiting"

# ── Manual test checklist: security ───────────────────────────────────────
stage "Test 5/7: security"
say "lib/slack_verifier.rb rejects anything not signed by Slack."
step "A request with an invalid signature is rejected with 401:"
note "  curl -i -X POST ${NGROK_URL:-http://localhost:4567}/slack/commands \\"
note "    -H 'X-Slack-Signature: v0=deadbeef' \\"
note "    -H \"X-Slack-Request-Timestamp: \$(date +%s)\" \\"
note "    -d 'command=/ping'"
step "A request with a timestamp older than 5 minutes is rejected:"
note "  same call, but with X-Slack-Request-Timestamp: \$(( \$(date +%s) - 400 ))"
step "A genuine Slack request is still accepted (any working /ping proves this)"
check_group "Security"

# ── Manual test checklist: error handling ─────────────────────────────────
stage "Test 6/7: error handling"
say "Every error must be ephemeral, visible only to whoever sent the command."
step "'User not found' shows an error to the sender"
step "Pinging someone with DMs disabled shows a graceful error, not a crash"
step "A Slack API failure shows a generic message rather than leaking internals"
step "Every error above was visible only to you, never posted into the channel"
note "The last one is the one to actually verify in a shared channel. An error"
note "that posts publicly turns a failed ping into a visible mistake."
check_group "Error handling"

# ── Manual test checklist: logging ────────────────────────────────────────
stage "Test 7/7: logging"
say "Ougai emits one JSON object per event. Check the terminal running the bot."
step "Output is JSON, one object per line, not plain text"
step "LOG_LEVEL=debug produces more output; LOG_LEVEL=warn produces less"
step "Structured fields are present, e.g. user_id and channel, not baked into the message"
step "Optional: piping through bunyan renders it readably"
note "Filter errors only:  cat log/production.log | jq 'select(.level == 50)'"
note "Ougai levels: 10 trace, 20 debug, 30 info, 40 warn, 50 error, 60 fatal."
check_group "Logging"

finish
